# Este archivo configura el selector de plantillas de issues para GitHub.
# No es una plantilla de issue, por eso no requiere name, description ni body.
blank_issues_enabled: false
contact_links:
  - name: Soporte de la comunidad
    url: https://github.com/ItsJhonAlex/michequera/discussions
    about: Pregunta o discute aqu√≠ temas generales del proyecto.